# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterbodyJsonGenerator
                                 A QGIS plugin
 Plugin generates waterbody polygons and polylines from a Json file based on class
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-29
        copyright            : (C) 2023 by PMO
        email                : PMO
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaterbodyJsonGenerator class from file WaterbodyJsonGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WaterbodyJsonGenerator import WaterbodyJsonGenerator
    return WaterbodyJsonGenerator(iface)
